// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "sample.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

class sampleHandler : virtual public sampleIf {
 public:
  sampleHandler() {
    // Your initialization goes here
  }

  void hello(std::string& _return, const std::string& value) {
    // Your implementation goes here
    printf("hello\n");
  }

  void ipaddr(std::string& _return) {
    // Your implementation goes here
    printf("ipaddr\n");
  }

  int32_t random(const int32_t num) {
    // Your implementation goes here
    printf("random\n");
  }

  void uuid(std::string& _return) {
    // Your implementation goes here
    printf("uuid\n");
  }

  void calculator(Calc& _return, const double num1, const double num2) {
    // Your implementation goes here
    printf("calculator\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::apache::thrift::stdcxx::shared_ptr<sampleHandler> handler(new sampleHandler());
  ::apache::thrift::stdcxx::shared_ptr<TProcessor> processor(new sampleProcessor(handler));
  ::apache::thrift::stdcxx::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::apache::thrift::stdcxx::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::apache::thrift::stdcxx::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

