/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef sample_CONSTANTS_H
#define sample_CONSTANTS_H

#include "sample_types.h"



class sampleConstants {
 public:
  sampleConstants();

};

extern const sampleConstants g_sample_constants;



#endif
