/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum ErrorCode
{
  ILLEGAL_ARGUMENT = 0,
  INVALID_IPADDR = 1,
  WINSOCK_FAILED = 2,
  INVALID_NUMERIC = 3,
  GENERATOR_FALIED = 4,
}
